### ISSUE TITLE
about 200 local variables limitation

### ISSUE THREAD

**Issue by RocFang** [api7/jsonschema#40]
Hello, @spacewander ,

The problem of 200 local variables limitation often occur to us when the json schema file geting bigger.
error info like:
```
main function has more than 200 local variables
```
I found 2 relative record from other repo:
1. https://github.com/Tieske/lua-resty-ljsonschema/pull/2
2. https://github.com/jdesgats/ljsonschema/issues/10

can we do this workaround too? thanks.

**Comment by membphis** [comment]
welcome PR, we can cherry-pick the commit ^_^

**Comment by RocFang** [comment]
@membphis  I have made a pr,
https://github.com/api7/jsonschema/pull/41

thanks for review.
