### ISSUE TITLE
Lua 5.2+ attempt to call a nil value (upvalue 'loadstring')

### ISSUE THREAD

**Issue by Quirynn** [api7/jsonschema#58]
Hey there.
The Bug is quite easy:

_jsonschema.lua line 261:_

`local loader, err = loadstring(tab_concat(self._code_table, ""), 'jsonschema:' .. (name or 'anonymous'))`

On my system with Lua 5.4 that line gives this error:
_attempt to call a nil value (upvalue 'loadstring')_

it works when I call it like this:

`local loader, err = load(tab_concat(self._code_table, ""), 'jsonschema:' .. (name or 'anonymous'))`

some solution would probably be:

`local loadfkt = loadstring or load`
`local loader, err = loadfkt(tab_concat(self._code_table, ""), 'jsonschema:' .. (name or 'anonymous'))`

**Comment by membphis** [comment]
welcome to submit a PR to fix this issue

**Comment by Quirynn** [comment]
I will do so asap

**Comment by membphis** [comment]
ping @Quirynn

**Comment by Quirynn** [comment]
Hey, sorry totally forgot about this.
I added a pull request.

Am Fr., 21. Jan. 2022 um 14:42 Uhr schrieb YuanSheng Wang <
***@***.***>:

**Comment by tzssangglass** [comment]
> do you plan to release it via LuaRocks?

hi @filipmnowak , has released on LuaRocks, ref: https://luarocks.org/modules/membphis/jsonschema
