### ISSUE TITLE
Cloning fails from GitHub via rockspec

### ISSUE THREAD

**Issue by arulrajnet** [api7/jsonschema#68]
This jsonschema is depends upon one of my module. 

While compiling that I am getting following error. 

![2022-01-11_06-01](https://user-images.githubusercontent.com/834529/148860737-fc9ea7f2-66b9-4b5a-b949-77c8d12ad667.png)

```
The unauthenticated git protocol on port 9418 is no longer supported.
```
No more unauthenticated git https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git

So Need to update the rockspec in https://github.com/api7/jsonschema/blob/master/rockspec/jsonschema-0.9.5-0.rockspec#L4 to https://github.com/api7/jsonschema/archive/refs/tags/v0.9.5.tar.gz

Updating older release rockspec files also recommented. 

@membphis

**Comment by tzssangglass** [comment]
It looks like you need to do something similar to this: https://github.com/apache/apisix-docker/pull/268/files

**Comment by tzssangglass** [comment]
sew github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git
and github.blog/2021-09-01-improving-git-protocol-security-github/#git-protocol-troubleshooting

**Comment by zicodes** [comment]
Thanks @tzssangglass 

Running ```git config --global url.https://github.com/.insteadOf git://github.com/``` on my local PC and then re-running `luarocks` worked for me.
