### ISSUE TITLE
Changing match_pattern can break predefined validators

### ISSUE THREAD

**Issue by Crack** [api7/jsonschema#7]
While looking at docs I noticed that I can pass a custom `match_pattern` implementation, but I also see that there are a few validations (eg. email, IPv4) that depend on it being PCRE-compatible.

Also, docs describe this parameter as:
> function called to match patterns, defaults to string.find.

while the code tries hard to use PCRE:

https://github.com/iresty/jsonschema/blob/f0a20ad7a64f90360a357c72e17bc1574be60ee6/lib/jsonschema.lua#L43-L52

 `string.find` is used only as a last resort, but then validators that depend on PCRE (eg. email, IPv4) will break.

It's not a problem for me, just reporting what I found.

**Comment by membphis** [comment]
Thanks for your report, I'll think about how to resolve this bug.

**Comment by Crack** [comment]
Maybe a possibility to pass custom implementations of `format` validations, which can override and/or extend provided ones? Along with a note that default format validations require PCRE from OpenResty / lrexlib-pcre?

**Comment by membphis** [comment]
Yes, that is much better.
