### ISSUE TITLE
feature: avoid using `yield`, which is not supported in some user cases.

### ISSUE THREAD

**Issue by membphis** [api7/jsonschema#8]
https://github.com/apache/incubator-apisix/issues/1181#issuecomment-593711676

**Comment by membphis** [comment]
we can pass an array table for storing the generating Lua code.

**Comment by membphis** [comment]
This is not easy, we need to be careful and add more test cases.

**Comment by sshniro** [comment]
Yes, I agree @membphis , I would prefer if anyone from the core team can fix it as I'm a beginner to Lua, in case if it is not in the immediate fix list, then I'll try to do this.

**Comment by membphis** [comment]
waiting for your PR ^_^

**Comment by sshniro** [comment]
I maybe not understanding the bigger picture here, when I remove the coroutine and simply append the code chunks to a table, it produces the same results as before. 

Can I get an example of where this approach can fail?

**Comment by sshniro** [comment]
Hi @membphis  a small clarification, maybe I'm not understanding the bigger picture here, when I remove the coroutine and simply append the code chunks to a table, it produces the same results as before.



> This is not easy

Can I know what things to watch out? and what is the reason to use coroutine here, as a table would also do the job, is it for any performance boost?

**Comment by membphis** [comment]
> Can I know what things to watch out? and what is the reason to use coroutine here, as a table would also do the job, is it for any performance boost?

our project base on https://github.com/jdesgats/ljsonschema , you can contact him for more detail things.

As I know, use coroutine is simple but bad performance. I would like the array table way which is better performance.
