### ISSUE TITLE
Error loading module 'posix.time' when running testcase Lua 5.3

### ISSUE THREAD

**Issue by sshniro** [api7/jsonschema#9]
Hi,

I'm using lua 5.3 and I was following the instruction in the readme file.
luarocks install lrexlib-pcre
luarocks install net_url
make dev
make test

```lua 

Makefile:39: warning: overriding recipe for target 'help'
Makefile:11: warning: ignoring old recipe for target 'help'
LUA_PATH="./lib/?.lua;/usr/local/share/lua/5.3/?.lua;/usr/local/share/lua/5.3/?/init.lua;/usr/local/lib/lua/5.3/?.lua;/usr/local/lib/lua/5.3/?/init.lua;./?.lua;./?/init.lua" LUA_CPATH="/usr/local/lib/lua/5.3/?.so;/usr/local/lib/lua/5.3/loadall.so;./?.so" resty t/draft4.lua
ERROR: t/draft4.lua:4: module 'posix.time' not found:
        no field package.preload['posix.time']
        no file '/usr/local/openresty/site/lualib/posix/time.ljbc'
```

**Comment by sshniro** [comment]
Its seems , the issue is linked with this: https://bugs.launchpad.net/ubuntu/+source/lua-posix/+bug/1752082
@moonming are you using lua 5.1 or are there any possible fix for this?

**Comment by membphis** [comment]
I mainly use Lua 5.1 now. 

I will try `lua 5.3 + luarocks` to confirm your error.

**Comment by membphis** [comment]
@sshniro please make a try with this PR ^_^

**Comment by sshniro** [comment]
Thanks, will test this.
